
function getField(item,...keys){for(const k of keys){const v=item&&item[k];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v;}return ''}
function getNumber(item,...keys){const v=getField(item,...keys);const n=Number(v);return Number.isFinite(n)?n:0}
function moneyZar(item){const cents=getNumber(item,'Price_Cents','price_cents','price');if(!cents)return 'Price not set';return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(cents/100)}
function normalizeType(item){return getField(item,'bundle_type','Bundle_Type','type')||'Package'}
function formatIncludedLabel(item){const total=getNumber(item,'file_count','Included_File_Count','included_file_count');if(!total)return 'Includes: —';if(total%2===0)return `Includes: ${total/2} Papers + ${total/2} Memos (${total} PDFs)`;return `Includes: ${total} PDFs`}
async function fetchStudyHubCatalog(){const tryUrls=[];if(window.STUDYHUB_CONFIG.liveCatalogUrl)tryUrls.push(window.STUDYHUB_CONFIG.liveCatalogUrl);tryUrls.push(window.STUDYHUB_CONFIG.fallbackCatalogUrl);const errors=[];for(const url of tryUrls){try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const payload=await res.json();return {payload,source:url,errors};}catch(err){errors.push(`${url}: ${err.message}`)}}throw new Error(errors.join('
'))}

const metaEl=document.getElementById('catalogMeta'),cardsRoot=document.getElementById('packageCards'),featuredRoot=document.getElementById('featuredCards'),filterType=document.getElementById('filterType'),filterProvince=document.getElementById('filterProvince'),filterSubject=document.getElementById('filterSubject'),sortBy=document.getElementById('sortBy'),clearFilters=document.getElementById('clearFilters'),searchInput=document.getElementById('searchInput'),contactForm=document.getElementById('contactForm');let catalogItems=[];
function featuredScore(item){const sku=String(getField(item,'sku','SKU')||'');const type=normalizeType(item);const files=getNumber(item,'file_count','Included_File_Count','included_file_count');let score=files;if(type==='Ultimate Bundle')score+=1000;if(type==='Master Bundle')score+=500;if(type==='Single Year')score+=250;if(type==='Single Subject')score+=150;if(sku.includes('SH-G'))score+=25;return score}
function formatCard(item,featured=false){const province=getField(item,'province_filter','Province_Filter')||'ALL';const subject=getField(item,'subject_or_all','subject_name','Subject_Name')||'ALL';const type=normalizeType(item);const sku=getField(item,'sku','SKU')||'';const notes=getField(item,'description','Notes','notes')||'Bundle generated from the StudyHub paper library.';const title=getField(item,'title')||`${sku||type}`;const yearRange=getField(item,'year_or_range')||'';const fromYear=getField(item,'Coverage_From_Year','coverage_from_year')||(yearRange?String(yearRange).split('-')[0]:'2022');const toYear=getField(item,'Coverage_To_Year','coverage_to_year')||(yearRange&&String(yearRange).includes('-')?String(yearRange).split('-')[1]:'2026');const tag=featured?'Featured bundle':type;return `<article class="card-surface"><span class="card-tag">${tag}</span><h3>${title}</h3><div class="badge-row"><span class="badge">${subject}</span><span class="badge">${province}</span></div><p>${notes}</p><ul><li>From year: ${fromYear}</li><li>To year: ${toYear}</li><li>${formatIncludedLabel(item)}</li></ul><div class="price-chip">${moneyZar(item)}</div><div class="card-actions"><a class="btn btn-secondary" href="package.html?sku=${encodeURIComponent(sku)}">View details</a><button class="btn btn-primary" type="button" onclick="window.location.href='checkout.html?sku=${encodeURIComponent(sku)}'">Buy bundle</button></div></article>`}
function uniqueSorted(list){return [...new Set(list.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b)))}
function populateFilters(items){const types=uniqueSorted(items.map(i=>normalizeType(i))),provinces=uniqueSorted(items.map(i=>getField(i,'province_filter','Province_Filter')||'ALL')),subjects=uniqueSorted(items.map(i=>getField(i,'subject_or_all','subject_name','Subject_Name')||'ALL'));if(filterType)filterType.innerHTML='<option value="ALL">All types</option>'+types.map(v=>`<option value="${v}">${v}</option>`).join('');if(filterProvince)filterProvince.innerHTML='<option value="ALL">All provinces</option>'+provinces.map(v=>`<option value="${v}">${v}</option>`).join('');if(filterSubject)filterSubject.innerHTML='<option value="ALL">All subjects</option>'+subjects.map(v=>`<option value="${v}">${v}</option>`).join('')}
function sortItems(items){const mode=sortBy?sortBy.value:'featured';const copy=[...items];if(mode==='priceAsc')copy.sort((a,b)=>getNumber(a,'price_cents','Price_Cents')-getNumber(b,'price_cents','Price_Cents'));else if(mode==='priceDesc')copy.sort((a,b)=>getNumber(b,'price_cents','Price_Cents')-getNumber(a,'price_cents','Price_Cents'));else if(mode==='filesDesc')copy.sort((a,b)=>getNumber(b,'file_count','Included_File_Count')-getNumber(a,'file_count','Included_File_Count'));else if(mode==='nameAsc')copy.sort((a,b)=>String(getField(a,'sku','SKU')).localeCompare(String(getField(b,'sku','SKU'))));else copy.sort((a,b)=>featuredScore(b)-featuredScore(a));return copy}
function renderFeatured(items){if(!featuredRoot)return;const featured=[...items].sort((a,b)=>featuredScore(b)-featuredScore(a)).slice(0,3);featuredRoot.innerHTML=featured.map(item=>formatCard(item,true)).join('')}
function applyFilters(){if(!cardsRoot)return;const type=filterType?filterType.value:'ALL',province=filterProvince?filterProvince.value:'ALL',subject=filterSubject?filterSubject.value:'ALL',term=(searchInput?searchInput.value:'').trim().toLowerCase();let filtered=catalogItems.filter(item=>{const itemType=normalizeType(item),itemProvince=getField(item,'province_filter','Province_Filter')||'ALL',itemSubject=getField(item,'subject_or_all','subject_name','Subject_Name')||'ALL',textBlob=[getField(item,'sku','SKU'),itemSubject,itemProvince,itemType,getField(item,'description','Notes','notes')].join(' ').toLowerCase();if(type!=='ALL'&&itemType!==type)return false;if(province!=='ALL'&&itemProvince!==province)return false;if(subject!=='ALL'&&itemSubject!==subject)return false;if(term&&!textBlob.includes(term))return false;return true});filtered=sortItems(filtered);cardsRoot.innerHTML=filtered.length?filtered.map(item=>formatCard(item,false)).join(''):'<article class="card-surface"><h3>No matches</h3><p>Try a different search, sort, or filter combination.</p></article>'}
async function loadCatalog(){try{const {payload,source}=await fetchStudyHubCatalog();catalogItems=payload.items||payload.packages||[];const generated=payload.generatedAt||payload.generated_at||'Unknown';const sourceLabel=source===window.STUDYHUB_CONFIG.fallbackCatalogUrl?'fallback sample data':'live catalog';if(metaEl){metaEl.textContent=`Loaded ${catalogItems.length} bundle rows from ${sourceLabel}. Generated: ${generated}`;metaEl.classList.add('status-ok')}populateFilters(catalogItems);renderFeatured(catalogItems);applyFilters()}catch(err){if(metaEl){metaEl.textContent='Catalog could not be loaded.';metaEl.classList.add('status-error')}if(cardsRoot)cardsRoot.innerHTML='<article class="card-surface"><h3>Catalog unavailable</h3><p>Check the live URL or fallback JSON file.</p></article>';if(featuredRoot)featuredRoot.innerHTML='';console.error(err)}}
[filterType,filterProvince,filterSubject,sortBy].forEach(el=>el&&el.addEventListener('change',applyFilters));if(searchInput)searchInput.addEventListener('input',applyFilters);if(clearFilters)clearFilters.addEventListener('click',()=>{filterType.value='ALL';filterProvince.value='ALL';filterSubject.value='ALL';sortBy.value='featured';searchInput.value='';applyFilters()});if(contactForm){contactForm.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(contactForm).entries());if(!window.STUDYHUB_CONFIG.apiBaseUrl||window.STUDYHUB_CONFIG.apiBaseUrl.includes('__PASTE')){alert('Contact form captured locally. Add your Apps Script URL in config.js to activate backend logging.');return}try{const res=await fetch(window.STUDYHUB_CONFIG.apiBaseUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'contact',...data})});if(!res.ok)throw new Error('Request failed');alert('Message sent.');contactForm.reset()}catch(err){alert('Contact endpoint is not active yet.')}})}
loadCatalog();document.querySelectorAll('[data-search]').forEach(btn=>btn.addEventListener('click',()=>{const term=btn.getAttribute('data-search')||'';if(searchInput){searchInput.value=term;searchInput.dispatchEvent(new Event('input',{bubbles:true}))}const target=document.getElementById('packages');if(target)target.scrollIntoView({behavior:'smooth'})}));
