/* StudyHub FINAL app.js */
(function(){
  const CFG = window.STUDYHUB_CONFIG || {};
  const $ = id => document.getElementById(id);
  let catalog = [];
  const esc = s => String(s ?? '').replace(/[&<>'"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const money = c => Number(c) > 0 ? new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(Number(c)/100) : 'Price not set';
  function webAppUrl(){ return String(CFG.WEBAPP_URL || CFG.webappUrl || CFG.apiBaseUrl || '').trim(); }
  function adminUrl(){ const base=webAppUrl(); return CFG.ADMIN_URL || (base ? base + '?page=admin' : 'admin/'); }
  function setStatus(text, cls){ if($('catalogMeta')){ $('catalogMeta').textContent=text; if(cls) $('catalogMeta').className=cls; } }
  function jsonp(action, params={}){return new Promise((resolve,reject)=>{const base=webAppUrl(); if(!base){reject(new Error('Web App URL missing in config.js'));return;} const cb='StudyHub_cb_'+Math.random().toString(36).slice(2)+Date.now(); const qs=new URLSearchParams(Object.assign({},params,{action,callback:cb,_ts:Date.now()})); const s=document.createElement('script'); let done=false; const timer=setTimeout(()=>{if(!done){cleanup();reject(new Error('Request timed out: '+action));}},30000); function cleanup(){done=true;clearTimeout(timer);try{delete window[cb]}catch(e){window[cb]=undefined} if(s.parentNode)s.remove();} window[cb]=data=>{cleanup();resolve(data)}; s.onerror=()=>{cleanup();reject(new Error('Network/API error: '+action));}; s.src=base+'?'+qs.toString(); document.body.appendChild(s);});}
  async function fetchJson(url){const r=await fetch(url,{cache:'no-store'}); if(!r.ok)throw new Error('HTTP '+r.status+' loading '+url); return await r.json();}
  async function fetchCatalog(){try{const j=await jsonp('catalogJsonp'); if(j&&j.ok)return j; throw new Error((j&&j.error)||'catalogJsonp failed');}catch(e){console.warn('catalogJsonp failed, falling back:',e)} const base=webAppUrl(); const urls=[CFG.liveCatalogUrl, base?base+'?action=catalog':'', CFG.fallbackCatalogUrl||'data/catalog.sample.json'].filter(Boolean); for(const u of urls){try{return await fetchJson(u)}catch(e){console.warn(e)}} throw new Error('Catalogue unavailable');}
  function norm(x){return{sku:String(x.sku||''),title:x.title||x.sku||'Bundle',type:x.bundle_type||x.type||'Bundle',grade:String(x.grade||''),subject:x.subject_or_all||x.subject||'ALL',year:x.year_or_range||x.year||'',price:Number(x.price_cents||x.price||0),files:Number(x.file_count||x.files||0),desc:x.description||'',zip_status:x.zip_status||'READY',published:x.published};}
  function score(i){return i.files+(i.type==='Ultimate'?5000:i.type==='Master'?2500:i.type==='Single Year'?1000:0)}
  function card(i, hot=false){const details='package.html?sku='+encodeURIComponent(i.sku); const checkout='checkout.html?sku='+encodeURIComponent(i.sku); const delivery=i.type==='Ultimate'?'Folder pack delivery':'ZIP delivery'; return `<article class="card"><span class="eyebrow">${hot?'Featured':esc(i.type)}</span><h3>${esc(i.title)}</h3><div class="badges"><span class="badge">Grade ${esc(i.grade||'8-12')}</span><span class="badge">${esc(i.subject)}</span><span class="badge">${esc(i.year)}</span><span class="badge">${esc(i.zip_status)}</span></div><p class="muted">${esc(i.desc||'Paper + memo bundle.')}</p><ul class="muted"><li>${esc(i.files)} files counted</li><li>${delivery} after PayFast confirmation</li></ul><div class="price">${money(i.price)}</div><div class="actions"><a class="btn btn-secondary secondary" href="${details}">Details</a><a class="btn btn-primary primary" href="${checkout}">Buy</a></div></article>`;}
  function fill(id, vals, label){const e=$(id); if(!e)return; const current=e.value||'ALL'; const options=[...new Set(vals.filter(Boolean))].sort(); e.innerHTML=`<option value="ALL">${esc(label)}</option>`+options.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join(''); if([...e.options].some(o=>o.value===current))e.value=current;}
  function render(){const term=($('searchInput')?.value||'').toLowerCase(); const type=$('filterType')?.value||'ALL'; const subject=$('filterSubject')?.value||'ALL'; const sort=$('sortBy')?.value||'featured'; let list=catalog.filter(i=>(type==='ALL'||i.type===type)&&(subject==='ALL'||i.subject===subject)&&(!term||[i.sku,i.title,i.type,i.grade,i.subject,i.year,i.desc].join(' ').toLowerCase().includes(term))); if(sort==='priceAsc')list.sort((a,b)=>a.price-b.price); else if(sort==='priceDesc')list.sort((a,b)=>b.price-a.price); else if(sort==='filesDesc')list.sort((a,b)=>b.files-a.files); else if(sort==='nameAsc')list.sort((a,b)=>a.title.localeCompare(b.title)); else list.sort((a,b)=>score(b)-score(a)); const featured=catalog.slice().sort((a,b)=>score(b)-score(a)).slice(0,3); if($('featuredCards'))$('featuredCards').innerHTML=featured.map(i=>card(i,true)).join(''); if($('packageCards'))$('packageCards').innerHTML=list.length?list.map(i=>card(i)).join(''):`<div class="panel"><h4>No matches</h4><p>Try clearing filters.</p></div>`;}
  async function init(){setupAdminLinks(); try{setStatus('Loading catalogue...',''); const payload=await fetchCatalog(); catalog=(payload.items||payload.packages||[]).filter(x=>String(x.published).toLowerCase()!=='false').filter(x=>!x.zip_status||String(x.zip_status).toUpperCase()==='READY').map(norm); setStatus(`Loaded ${catalog.length} bundles from ${payload.generated_at?'live backend':'catalogue'}.`,'ok'); if($('statBundles'))$('statBundles').textContent=catalog.length; fill('filterType',catalog.map(i=>i.type),'All types'); fill('filterSubject',catalog.map(i=>i.subject),'All subjects'); render();}catch(e){console.error(e); setStatus('Could not load catalogue. Check Apps Script deployment/config.','bad');}}
  function setupAdminLinks(){document.querySelectorAll('.admin-link, a[href="admin/"], a[href="admin/index.html"]').forEach(a=>{a.href=adminUrl();a.target='_blank';});}
  ['filterType','filterSubject','sortBy'].forEach(id=>$(id)?.addEventListener('change',render)); $('searchInput')?.addEventListener('input',render); $('clearFilters')?.addEventListener('click',()=>{if($('searchInput'))$('searchInput').value=''; if($('filterType'))$('filterType').value='ALL'; if($('filterSubject'))$('filterSubject').value='ALL'; if($('sortBy'))$('sortBy').value='featured'; render();}); document.querySelectorAll('[data-search]').forEach(b=>b.addEventListener('click',()=>{if($('searchInput'))$('searchInput').value=b.dataset.search||''; render(); document.getElementById('bundles')?.scrollIntoView({behavior:'smooth'});}));
  window.StudyHub={loadCatalog:init,render}; init();
})();
