const cfg=window.STUDYHUB_CONFIG||{};
const val=(o,...ks)=>{for(const k of ks)if(o&&o[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k];return''};
const cents=o=>Number(val(o,'price_cents','Price_Cents')||0);
const money=o=>cents(o)?new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(cents(o)/100):'Price TBC';
const sku=o=>val(o,'sku','SKU'), type=o=>val(o,'bundle_type','Bundle_Type','type')||'Bundle';
const grade=o=>String(val(o,'grade','Grade')||''), subject=o=>val(o,'subject_or_all','Subject_Name','subject_name')||'ALL';
const yr=o=>val(o,'year_or_range','Coverage_To_Year','year')||'Available years', files=o=>Number(val(o,'file_count','Included_File_Count')||0);
let catalogItems=[];
async function fetchCatalog(){const url=cfg.liveCatalogUrl;if(!url)throw Error('Live catalog URL is not configured');const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();if(j.ok===false)throw Error(j.error||'Catalog request failed');const data=j.data||j.items||j.packages||j;return Array.isArray(data)?data:(data.items||data.packages||[])}
function score(o){let s=files(o);const t=type(o).toLowerCase();if(t.includes('ultimate'))s+=900;if(t.includes('master'))s+=500;if(String(subject(o)).includes('PART-'))s-=100;return s}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function gradeClass(o){return 'g'+(grade(o)||'all')}
function card(o,featured=false){const id=sku(o), t=type(o), g=grade(o), sub=subject(o), y=yr(o), pairs=Number(val(o,'pair_count')||0);return `<article class="product-card ${gradeClass(o)} ${featured?'featured-card':''}"><div class="product-top"><span class="bundle-badge">${esc(t)}</span><span class="ready-badge"><i></i> ZIP ready</span></div><div class="grade-watermark">${esc(g)}</div><h3>${esc(val(o,'title','Title')||id)}</h3><div class="badge-row"><span>Grade ${esc(g)}</span><span>${esc(sub)}</span><span>${esc(y)}</span></div><p>${esc(val(o,'description','notes','Notes')||'Verified exam paper and memo bundle for focused revision.')}</p><div class="product-stats"><div><strong>${pairs||'✓'}</strong><small>paper + memo pairs</small></div><div><strong>${files(o)}</strong><small>files in ZIP</small></div></div><div class="product-footer"><div><small>Secure digital delivery</small><strong class="price">${money(o)}</strong></div><a class="arrow-btn" href="package.html?sku=${encodeURIComponent(id)}" aria-label="View ${esc(id)}">→</a></div></article>`}
function fillSelect(id,items,label){const el=document.getElementById(id);if(!el)return;el.innerHTML=`<option value="ALL">${label}</option>`+[...new Set(items.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true})).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function applyFilters(){const term=(document.getElementById('searchInput')?.value||'').toLowerCase(),ft=document.getElementById('filterType')?.value||'ALL',fg=document.getElementById('filterGrade')?.value||'ALL',fs=document.getElementById('filterSubject')?.value||'ALL',sort=document.getElementById('sortBy')?.value||'featured';let rows=catalogItems.filter(o=>{const blob=[sku(o),type(o),'Grade '+grade(o),subject(o),yr(o),val(o,'title','Title')].join(' ').toLowerCase();return (ft==='ALL'||type(o)===ft)&&(fg==='ALL'||grade(o)===fg)&&(fs==='ALL'||subject(o)===fs)&&(!term||blob.includes(term))});if(sort==='priceAsc')rows.sort((a,b)=>cents(a)-cents(b));else if(sort==='priceDesc')rows.sort((a,b)=>cents(b)-cents(a));else if(sort==='filesDesc')rows.sort((a,b)=>files(b)-files(a));else rows.sort((a,b)=>score(b)-score(a));document.getElementById('packageCards').innerHTML=rows.length?rows.map(o=>card(o)).join(''):`<div class="empty-state"><b>No matching live bundles</b><span>Try another grade, subject or year.</span></div>`}
async function init(){const meta=document.getElementById('catalogMeta');try{catalogItems=(await fetchCatalog()).filter(o=>String(val(o,'published')).toUpperCase()==='TRUE'&&String(val(o,'zip_status')).toUpperCase()==='READY');meta.textContent=`${catalogItems.length} verified packages available now.`;meta.className='status-ok';document.getElementById('heroBundleCount').textContent=catalogItems.length||'Live';fillSelect('filterType',catalogItems.map(type),'All bundle types');fillSelect('filterGrade',catalogItems.map(grade),'All grades');fillSelect('filterSubject',catalogItems.map(subject),'All subjects');document.getElementById('featuredCards').classList.remove('skeleton-grid');document.getElementById('featuredCards').innerHTML=catalogItems.length?[...catalogItems].sort((a,b)=>score(b)-score(a)).slice(0,3).map(o=>card(o,true)).join(''):`<div class="empty-state"><b>Catalog awaiting publication</b><span>Verified ZIPs will appear when approved in the StudyHub Catalog.</span></div>`;applyFilters()}catch(e){meta.textContent='Live catalog connection is not ready: '+e.message;meta.className='status-error';document.getElementById('featuredCards').innerHTML='';document.getElementById('packageCards').innerHTML=`<div class="empty-state"><b>Catalog temporarily unavailable</b><span>Please try again shortly.</span></div>`}}
['filterType','filterGrade','filterSubject','sortBy'].forEach(id=>document.getElementById(id)?.addEventListener('change',applyFilters));document.getElementById('searchInput')?.addEventListener('input',applyFilters);document.getElementById('clearFilters')?.addEventListener('click',()=>{['filterType','filterGrade','filterSubject'].forEach(id=>document.getElementById(id).value='ALL');document.getElementById('searchInput').value='';applyFilters()});document.querySelectorAll('[data-search]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('searchInput').value=b.dataset.search;applyFilters();document.getElementById('packages').scrollIntoView({behavior:'smooth'})}));init();
