
function getField(item,...keys){for(const k of keys){const v=item&&item[k];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v;}return ''}
function getNumber(item,...keys){const v=getField(item,...keys);const n=Number(v);return Number.isFinite(n)?n:0}
function moneyZar(item){const cents=getNumber(item,'Price_Cents','price_cents','price');if(!cents)return 'Price not set';return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(cents/100)}
function normalizeType(item){return getField(item,'bundle_type','Bundle_Type','type')||'Package'}
function formatIncludedLabel(item){const total=getNumber(item,'file_count','Included_File_Count','included_file_count');if(!total)return 'Includes: —';if(total%2===0)return `Includes: ${total/2} Papers + ${total/2} Memos (${total} PDFs)`;return `Includes: ${total} PDFs`}
async function fetchStudyHubCatalog(){const tryUrls=[];if(window.STUDYHUB_CONFIG.liveCatalogUrl)tryUrls.push(window.STUDYHUB_CONFIG.liveCatalogUrl);tryUrls.push(window.STUDYHUB_CONFIG.fallbackCatalogUrl);const errors=[];for(const url of tryUrls){try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const payload=await res.json();return {payload,source:url,errors};}catch(err){errors.push(`${url}: ${err.message}`)}}throw new Error(errors.join('
'))}

const sku=new URL(window.location.href).searchParams.get('sku')||'';const titleEl=document.getElementById('checkoutTitle'),introEl=document.getElementById('checkoutIntro'),skuField=document.getElementById('skuField'),priceEl=document.getElementById('checkoutPrice'),badgesEl=document.getElementById('checkoutBadges'),fromYearMeta=document.getElementById('fromYearMeta'),toYearMeta=document.getElementById('toYearMeta'),filesMeta=document.getElementById('filesMeta'),checkoutForm=document.getElementById('checkoutForm'),checkoutStatus=document.getElementById('checkoutStatus'),payLaterBtn=document.getElementById('payLaterBtn');let currentItem=null;
async function loadCheckout(){if(!sku){titleEl.textContent='Missing bundle';introEl.textContent='Open checkout with ?sku=YOUR_SKU';return}skuField.value=sku;try{const {payload}=await fetchStudyHubCatalog();const items=payload.items||payload.packages||[];currentItem=items.find(v=>String(getField(v,'SKU','sku')||'')===sku);if(!currentItem){titleEl.textContent='Bundle not found';introEl.textContent=`No bundle with SKU ${sku} was found.`;return}const yearRange=getField(currentItem,'year_or_range')||'';titleEl.textContent=`Checkout — ${getField(currentItem,'title')||sku}`;introEl.textContent='Secure PayFast checkout. Your ZIP delivery link appears after payment confirmation.';priceEl.textContent=moneyZar(currentItem);badgesEl.innerHTML=`<span class="badge">${getField(currentItem,'subject_or_all','Subject_Name')||'ALL'}</span><span class="badge">${getField(currentItem,'province_filter','Province_Filter')||'ALL'}</span>`;fromYearMeta.textContent=getField(currentItem,'Coverage_From_Year','coverage_from_year')||(yearRange?String(yearRange).split('-')[0]:'2022');toYearMeta.textContent=getField(currentItem,'Coverage_To_Year','coverage_to_year')||(yearRange&&String(yearRange).includes('-')?String(yearRange).split('-')[1]:'2026');filesMeta.textContent=formatIncludedLabel(currentItem)}catch(err){titleEl.textContent='Catalog unavailable';introEl.textContent='The bundle could not be loaded.'}}
if(payLaterBtn)payLaterBtn.addEventListener('click',()=>alert('Questions first? Use the contact section on the home page and StudyHub will help.'));if(checkoutForm){checkoutForm.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(checkoutForm).entries());if(!window.STUDYHUB_CONFIG.apiBaseUrl||window.STUDYHUB_CONFIG.apiBaseUrl.includes('__PASTE')){checkoutStatus.textContent='Set your Apps Script Web App URL in config.js before going live.';checkoutStatus.classList.add('notice');return}try{const payload={action:'createCheckout',sku:sku,email:data.customer_email,customer_email:data.customer_email,customer_name:data.customer_name,customer_phone:data.customer_phone,notes:data.notes};const res=await fetch(window.STUDYHUB_CONFIG.apiBaseUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error('Order request failed');const out=await res.json();if(out&&out.ok&&out.order_id&&out.payfast_url&&out.payfast_payload){localStorage.setItem('studyhub_last_order_id',out.order_id);const form=document.createElement('form');form.method='POST';form.action=out.payfast_url;Object.entries(out.payfast_payload).forEach(([k,v])=>{const input=document.createElement('input');input.type='hidden';input.name=k;input.value=String(v);form.appendChild(input)});document.body.appendChild(form);form.submit();return}throw new Error('Checkout response missing PayFast payload.')}catch(err){checkoutStatus.textContent='Checkout could not start. Check apiBaseUrl, Script Properties, and PayFast settings.';checkoutStatus.classList.add('notice')}})}
loadCheckout();
