const cfg=window.STUDYHUB_CONFIG||{};
const val=(o,...ks)=>{for(const k of ks)if(o&&o[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k];return''};
const money=c=>Number(c||0)===0?'FREE':new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(Number(c)/100);
const wanted=new URL(location.href).searchParams.get('sku')||'';
let product=null;
async function fetchCatalog(){const r=await fetch(cfg.liveCatalogUrl,{cache:'no-store'});if(!r.ok)throw Error('Catalog HTTP '+r.status);const j=await r.json();if(j.ok===false)throw Error(j.error||'Catalog unavailable');return Array.isArray(j.data)?j.data:[]}
async function init(){document.getElementById('skuField').value=wanted;if(!wanted){document.getElementById('checkoutTitle').textContent='Missing bundle SKU';return}try{const rows=await fetchCatalog();product=rows.find(x=>String(val(x,'sku','SKU'))===wanted);if(!product)throw Error('Bundle not found');document.getElementById('checkoutTitle').textContent=val(product,'title')||wanted;document.getElementById('checkoutIntro').textContent='Enter the delivery details, then continue to PayFast.';document.getElementById('checkoutPrice').textContent=money(val(product,'price_cents'));document.getElementById('checkoutBadges').innerHTML=`<span>Grade ${val(product,'grade')}</span><span>${val(product,'bundle_type')}</span><span>${val(product,'subject_or_all')}</span>`;document.getElementById('yearMeta').textContent=val(product,'year_or_range')||'Available';document.getElementById('pairsMeta').textContent=val(product,'pair_count')||0;document.getElementById('filesMeta').textContent=val(product,'file_count')||0}catch(e){document.getElementById('checkoutTitle').textContent='Bundle unavailable';document.getElementById('checkoutIntro').textContent=e.message;document.querySelector('#checkoutForm button').disabled=true}}
document.getElementById('checkoutForm').addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('checkoutStatus');if(!product){status.textContent='Bundle is not ready.';status.className='checkout-status error';return}if(!document.getElementById('termsCheck').checked){status.textContent='Please accept the Terms and Refund Policy.';status.className='checkout-status error';return}const data=Object.fromEntries(new FormData(e.target).entries());status.textContent='Creating secure PayFast checkout...';status.className='checkout-status warning';try{const q=new URLSearchParams({api:'checkout',sku:wanted,customer_email:data.customer_email,customer_name:data.customer_name||'',customer_phone:data.customer_phone||''});const r=await fetch(cfg.apiBaseUrl+'?'+q.toString(),{cache:'no-store'});const out=await r.json();if(!out.ok)throw Error(out.error||'Checkout failed');const url=out.data?.url||out.url;if(!url)throw Error('Payment URL was not returned');location.href=url}catch(err){status.textContent='Checkout could not start: '+err.message;status.className='checkout-status error'}});
init();
