
function getField(item,...keys){for(const k of keys){const v=item&&item[k];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v;}return ''}
function getNumber(item,...keys){const v=getField(item,...keys);const n=Number(v);return Number.isFinite(n)?n:0}
function moneyZar(item){const cents=getNumber(item,'Price_Cents','price_cents','price');if(!cents)return 'Price not set';return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(cents/100)}
function normalizeType(item){return getField(item,'bundle_type','Bundle_Type','type')||'Package'}
function formatIncludedLabel(item){const total=getNumber(item,'file_count','Included_File_Count','included_file_count');if(!total)return 'Includes: —';if(total%2===0)return `Includes: ${total/2} Papers + ${total/2} Memos (${total} PDFs)`;return `Includes: ${total} PDFs`}
async function fetchStudyHubCatalog(){const tryUrls=[];if(window.STUDYHUB_CONFIG.liveCatalogUrl)tryUrls.push(window.STUDYHUB_CONFIG.liveCatalogUrl);tryUrls.push(window.STUDYHUB_CONFIG.fallbackCatalogUrl);const errors=[];for(const url of tryUrls){try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const payload=await res.json();return {payload,source:url,errors};}catch(err){errors.push(`${url}: ${err.message}`)}}throw new Error(errors.join('
'))}

const detailStatus=document.getElementById('detailStatus'),detailRoot=document.getElementById('packageDetailRoot');function getSkuFromUrl(){return new URL(window.location.href).searchParams.get('sku')||''}
function detailMarkup(item){const sku=getField(item,'sku','SKU')||'';const title=getField(item,'title')||sku||'Bundle';const type=normalizeType(item);const province=getField(item,'province_filter','Province_Filter')||'ALL';const subject=getField(item,'subject_or_all','Subject_Name','subject_name')||'ALL';const yearRange=getField(item,'year_or_range')||'';const fromYear=getField(item,'Coverage_From_Year','coverage_from_year')||(yearRange?String(yearRange).split('-')[0]:'2022');const toYear=getField(item,'Coverage_To_Year','coverage_to_year')||(yearRange&&String(yearRange).includes('-')?String(yearRange).split('-')[1]:'2026');const notes=getField(item,'description','Notes','notes')||'No description available.';const included=formatIncludedLabel(item);const price=moneyZar(item);return `<div class="detail-layout"><section class="detail-panel card-surface"><span class="eyebrow">Bundle detail</span><h2>${title}</h2><p class="product-note">${notes.replace(/
/g,'<br>')}</p><div class="badge-row" style="margin-top:12px"><span class="badge">${type}</span><span class="badge">${subject}</span><span class="badge">${province}</span></div><div class="detail-actions" style="margin-top:18px"><a class="btn btn-primary" href="checkout.html?sku=${encodeURIComponent(sku)}">Buy bundle</a><a class="btn btn-secondary" href="index.html#packages">Back to catalog</a></div><p class="product-note" style="margin-top:14px">Every bundle combines question papers and memorandums to help revision and self-marking.</p></section><aside class="detail-panel card-surface product-sidebar"><h3>Summary</h3><div class="product-price">${price}</div><div class="detail-meta-list"><div class="detail-meta-item"><strong>From year</strong><span>${fromYear}</span></div><div class="detail-meta-item"><strong>To year</strong><span>${toYear}</span></div><div class="detail-meta-item"><strong>Included (Papers + Memos)</strong><span>${included}</span></div><div class="detail-meta-item"><strong>SKU</strong><span>${sku}</span></div></div></aside></div>`}
async function loadPackageDetail(){const sku=getSkuFromUrl();if(!sku){detailStatus.innerHTML='<span class="eyebrow">Bundle detail</span><h2>Missing bundle SKU</h2><p>Open this page with <code>?sku=YOUR_SKU</code>.</p>';return}try{const {payload,source}=await fetchStudyHubCatalog();const items=payload.items||payload.packages||[];const item=items.find(v=>String(getField(v,'SKU','sku')||'')===sku);if(!item){detailStatus.innerHTML=`<span class="eyebrow">Bundle detail</span><h2>Bundle not found</h2><p>No bundle with SKU <code>${sku}</code> was found.</p>`;return}const sourceLabel=source===window.STUDYHUB_CONFIG.fallbackCatalogUrl?'fallback sample data':'live catalog';detailStatus.innerHTML=`<span class="eyebrow">Bundle detail</span><h2>${getField(item,'title')||sku}</h2><p>Loaded from ${sourceLabel}.</p>`;detailRoot.innerHTML=detailMarkup(item)}catch(err){detailStatus.innerHTML='<span class="eyebrow">Bundle detail</span><h2>Catalog unavailable</h2><p>The bundle detail could not be loaded.</p>';console.error(err)}}
loadPackageDetail();
