const QH=['timestamp','provider','source_url','province','grade','subject','year','language','assessment_type','paper_type','paper_file_type','memo_file_type','paper_url','memo_url','status','source_folder_url','notes'];
function startScannerLinksImport(){props().setProperties({SL_IMPORT_RUNNING:'TRUE',SL_IMPORT_STOP_REQUESTED:'FALSE'},false);return runScannerLinksImportBatch()}
function stopScannerLinksImport(){props().setProperty('SL_IMPORT_RUNNING','FALSE');return scannerLinksImportStatus()}
function resetScannerLinksImport(){props().setProperties({SL_IMPORT_CURSOR:'2',SL_IMPORT_RUNNING:'FALSE'},false);return scannerLinksImportStatus()}
function scannerLinksImportStatus(){return{running:props().getProperty('SL_IMPORT_RUNNING')==='TRUE',cursor:Number(props().getProperty('SL_IMPORT_CURSOR')||2),lastRun:props().getProperty('SL_IMPORT_LAST_RUN')||''}}
function runScannerLinksImportBatch(){return lock('scan',()=>{if(props().getProperty('SL_IMPORT_RUNNING')!=='TRUE')return{status:'STOPPED'};const s=db().getSheetByName('ScannerLinks');if(!s)throw Error('ScannerLinks missing');const a=s.getDataRange().getValues(),h=a.shift().map(x=>String(x).toLowerCase().replace(/[^a-z0-9]+/g,'_')),cur=Number(props().getProperty('SL_IMPORT_CURSOR')||2),size=Number(props().getProperty('SL_IMPORT_BATCH_SIZE')||1000),slice=a.slice(cur-2,cur-2+size),all=slice.map((r,i)=>parseLink(rowObj(h,r),cur+i)).filter(Boolean),groups={};all.forEach(x=>{(groups[x.key]=groups[x.key]||{P:[],M:[]})[x.role].push(x)});const q=tab(APP.Q,QH),existing=new Set(objects(q).map(x=>x.paper_url+'|'+x.memo_url)),rows=[];Object.values(groups).forEach(g=>{const n=Math.min(g.P.length,g.M.length);for(let i=0;i<n;i++){const p=g.P[i],m=g.M[i],k=p.url+'|'+m.url;if(existing.has(k))continue;existing.add(k);rows.push([new Date(),p.provider,p.source,p.province,p.grade,p.subject,p.year,p.language,p.assessment,p.paperType,p.fileType,m.fileType,p.url,m.url,'VALIDATED','',`ScannerLinks ${p.row}/${m.row}`])}});if(rows.length)q.getRange(q.getLastRow()+1,1,rows.length,QH.length).setValues(rows);const next=cur+slice.length,done=next>s.getLastRow();props().setProperties({SL_IMPORT_CURSOR:String(done?2:next),SL_IMPORT_RUNNING:done?'FALSE':'TRUE',SL_IMPORT_LAST_RUN:new Date().toISOString()},false);log('SCAN_BATCH','ScannerLinks','OK',`read=${slice.length}, imported=${rows.length}`);return{status:done?'COMPLETE':'RUNNING',read:slice.length,imported:rows.length,next:done?null:next}})}
function rowObj(h,r){const o={};h.forEach((k,i)=>o[k]=r[i]);return o}
function parseLink(o,row){const text=[o.link_text,o.filename,o.subject,o.link_url].join(' '),url=String(o.link_url||'').replace(/&amp;/g,'&');let grade=String(o.grade||'').match(/\b(8|9|10|11|12)\b/),year=String(o.year||text).match(/\b(20(?:2[2-9]|[3-9]\d))\b/);if(!grade||!year||!/^https?:/i.test(url))return null;const language=/afrikaans|\bafr\b/i.test(text)?'Afrikaans':(/english|\beng\b/i.test(text)?'English':'');if(!language)return null;if(/\bSAL\b|second additional|isin?debele|isizulu|isixhosa|sesotho|setswana|sepedi|tshivenda|siswati/i.test(text))return null;const subject=subjectOf(text);if(!subject)return null;const memo=/memo|memorandum|marking|answers?/i.test(text),paper=/question|exam paper|test paper|\bpaper\b|\bqp\b/i.test(text);if(!memo&&!paper)return null;const pt=(text.match(/(?:paper|\bP)[ _-]?([123])\b/i)||[])[1],assessment=/trial|prelim/i.test(text)?'Trial Exam':(/june/i.test(text)?'June Exam':(/november|final/i.test(text)?'November Exam':(/test/i.test(text)?'Test':'Exam')));const provider=String(o.provider||'ApprovedSource'),province=String(o.province||'National');return{row,url,source:String(o.source_url||''),provider,province,grade:grade[1],year:year[1],language,subject,assessment,paperType:pt?'P'+pt:'Other',fileType:/\.zip/i.test(url)?'ZIP':'PDF',role:memo?'M':'P',key:[provider,province,grade[1],subject,year[1],language,assessment,pt||'Other'].join('|')}}
function subjectOf(t){const a=[['Economic and Management Sciences (EMS)',/economic.*management|\bEMS\b/i],['Mathematical Literacy',/mathematical literacy|maths? lit|wiskundige geletterdheid/i],['Physical Sciences',/physical science|fisiese wetenskap/i],['Natural Sciences',/natural science|natuurwetenskap/i],['Social Sciences',/social science|sosiale wetenskap/i],['Life Sciences',/life science|lewenswetenskap/i],['Business Studies',/business studies|besigheidstudies/i],['Creative Arts',/creative arts|skeppende kunste/i],['Accounting',/accounting|rekeningkunde/i],['Economics',/economics|ekonomie/i],['Geography',/geography|geografie/i],['History',/history|geskiedenis/i],['Technology',/technology|tegnologie/i],['Mathematics',/mathematics|maths|wiskunde/i],['Afrikaans FAL',/afrikaans.*(?:FAL|first additional)/i],['Afrikaans HL',/afrikaans.*(?:HL|home language|huistaal)/i],['English FAL',/english.*(?:FAL|first additional)/i],['English HL',/english.*(?:HL|home language)/i]];for(const x of a)if(x[1].test(t))return x[0];return''}
