const $=id=>document.getElementById(id);let rows=[];const savedApi=localStorage.getItem('studyhubAdminApi')||(window.STUDYHUB_CONFIG?.apiBaseUrl||'');$('api').value=savedApi;
function params(api,extra={}){const base=$('api').value.trim(),token=$('token').value.trim();if(!base||!token)throw Error('Enter the API URL and admin token.');localStorage.setItem('studyhubAdminApi',base);return{base,q:new URLSearchParams({api,token,...extra})}}
async function call(api,extra={}){const {base,q}=params(api,extra);const r=await fetch(base+'?'+q.toString(),{cache:'no-store'});const j=await r.json();if(!j.ok)throw Error(j.error||'Request failed');return j.data}
function msg(t,c=''){$('message').textContent=t;$('message').className='message '+c}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(summary){rows=summary.orders||[];$('stats').innerHTML=[['Orders',rows.length],['Paid',rows.filter(x=>['COMPLETE','MANUAL_PAID'].includes(String(x.pf_status).toUpperCase())).length],['Pending',rows.filter(x=>String(x.pf_status).toUpperCase()==='PENDING').length],['Delivered',rows.filter(x=>String(x.delivery_status).toUpperCase()==='DELIVERY_SENT').length]].map(x=>`<div class="stat"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');apply()}
function apply(){const term=$('search').value.toLowerCase(),sf=$('statusFilter').value;const list=rows.filter(o=>{const blob=[o.order_id,o.customer_email,o.customer_name,o.sku,o.title,o.pf_status].join(' ').toLowerCase();return(!term||blob.includes(term))&&(sf==='ALL'||String(o.pf_status).toUpperCase()===sf)});$('orders').innerHTML=list.length?list.map(card).join(''):'<div class="message">No matching orders.</div>';}
function card(o){const paid=['COMPLETE','MANUAL_PAID'].includes(String(o.pf_status).toUpperCase());const email=encodeURIComponent(o.customer_email||'');const subject=encodeURIComponent('StudyHub order '+(o.order_id||''));return`<article class="order"><div class="order-head"><strong>${esc(o.order_id)}</strong><span class="pill ${paid?'paid':''}">${esc(o.pf_status||'PENDING')}</span></div><div class="order-grid"><div><small>Customer</small><b>${esc(o.customer_name||'—')}</b></div><div><small>Email</small><b>${esc(o.customer_email||'—')}</b></div><div><small>Bundle</small><b>${esc(o.sku||'—')}</b></div><div><small>Amount</small><b>R ${(Number(o.amount_cents||0)/100).toFixed(2)}</b></div><div><small>Delivery</small><b>${esc(o.delivery_status||'PENDING')}</b></div></div><div class="order-actions"><button onclick="act('mark_paid','${esc(o.order_id)}')">Mark paid + deliver</button><button class="secondary" onclick="act('mark_unpaid','${esc(o.order_id)}')">Mark unpaid</button><button onclick="act('grant_download','${esc(o.order_id)}')">Grant download</button><button class="danger" onclick="act('revoke_download','${esc(o.order_id)}')">Revoke</button><button class="secondary" onclick="act('resend_email','${esc(o.order_id)}')">Resend email</button><a href="mailto:${email}?subject=${subject}">Open email</a>${o.zip_url?`<a href="${esc(o.zip_url)}" target="_blank">Open ZIP</a>`:''}</div></article>`}
async function load(){try{msg('Loading orders...');const data=await call('adminSummary');render(data);msg('Admin data loaded.','ok')}catch(e){msg(e.message,'error')}}
window.act=async(action,order_id)=>{if(!confirm('Run '+action+' for '+order_id+'?'))return;try{msg('Working...');await call('adminAction',{action,order_id});await load()}catch(e){msg(e.message,'error')}};
$('connect').onclick=load;$('refresh').onclick=load;$('search').oninput=apply;$('statusFilter').onchange=apply;
