const cfg=window.STUDYHUB_CONFIG||{};const API=cfg.apiBaseUrl||cfg.webappUrl||'';const content=document.getElementById('content');const title=document.getElementById('title');const apiStatus=document.getElementById('apiStatus');let current='dashboard';
function money(c){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format((Number(c)||0)/100)}
function esc(v){return String(v??'').replace(/[&<>"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[s]))}
async function api(action,payload={}){if(!API)throw new Error('Backend URL missing in config.js');const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});if(!res.ok)throw new Error('HTTP '+res.status);const out=await res.json();if(out&&out.ok===false)throw new Error(out.error||'Backend returned ok=false');return out}
function setStatus(msg,cls=''){apiStatus.textContent=msg;apiStatus.className='muted '+cls}
function card(label,value,cls=''){return `<div class="card"><strong>${label}</strong><b class="${cls}">${value}</b></div>`}
function table(rows,cols){if(!rows||!rows.length)return '<div class="empty">No records found.</div>';return `<div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${c.label}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(c.fn?c.fn(r):r[c.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
async function renderDashboard(){content.innerHTML='<div class="empty">Loading dashboard…</div>';const d=await api('adminDashboardSummary');content.innerHTML=`<div class="grid">${card('Products',d.products??0)}${card('ZIPs Ready',d.zips_ready??0,'status-ok')}${card('Orders Today',d.orders_today??0)}${card('Revenue Today',money(d.revenue_today_cents||0))}${card('Scanner',d.scanner?.mode||'—')}${card('Downloads',d.downloads?.running?'Running':'Stopped')}${card('Bundles',d.bundles?.enabled?'Enabled':'Stopped')}${card('ZIP Total',d.zips?.total??0)}</div><div class="actions"><button class="btn" onclick="runAction('adminRunHealthCheck')">Run Health Check</button><button class="btn secondary" onclick="runAction('adminRunScannerNow')">Run Discovery Now</button><button class="btn secondary" onclick="runAction('adminStartDownloads')">Start Downloads</button><button class="btn secondary" onclick="runAction('adminBuildMissingZips')">Build Missing ZIPs</button></div>`}
async function renderOrders(){content.innerHTML='<div class="empty">Loading orders…</div>';const d=await api('adminListOrders');content.innerHTML=table(d.orders||[],[{label:'Date',key:'timestamp'},{label:'Order ID',key:'order_id'},{label:'Customer',key:'customer_email'},{label:'SKU',key:'sku'},{label:'Amount',fn:r=>money(r.amount_cents)},{label:'PayFast',key:'pf_status'},{label:'Delivery',key:'delivery_status'},{label:'Actions',fn:r=>`Resend: use API adminResendDelivery with ${r.order_id}`}])}
async function renderCatalog(){content.innerHTML='<div class="empty">Loading catalog…</div>';const d=await api('adminListCatalog');content.innerHTML=table(d.items||[],[{label:'SKU',key:'sku'},{label:'Title',key:'title'},{label:'Type',key:'bundle_type'},{label:'Grade',key:'grade'},{label:'Subject',key:'subject_or_all'},{label:'Price',fn:r=>money(r.price_cents)},{label:'ZIP',key:'zip_status'}])}
async function renderQueue(){const d=await api('adminQueueSummary');content.innerHTML=`<div class="grid">${card('Queue Total',d.total??0)}${Object.entries(d.by_status||{}).map(([k,v])=>card(k,v)).join('')}</div><pre>${esc(JSON.stringify(d.by_status||{},null,2))}</pre>`}
async function renderScanner(){const d=await api('adminScannerStatus');content.innerHTML=`<div class="grid">${card('Mode',d.mode)}${card('Running',d.running?'Yes':'No')}${card('Cursor',d.cursor)}${card('Batch Size',d.batch_size)}</div><div class="actions"><button class="btn" onclick="runAction('adminRunScannerNow')">Run Now</button><button class="btn secondary" onclick="runAction('adminStartScanner')">Start</button><button class="btn secondary" onclick="runAction('adminStopScanner')">Stop</button></div><pre>${esc(JSON.stringify(d,null,2))}</pre>`}
async function renderDownloads(){const d=await api('adminDownloadStatus');content.innerHTML=`<div class="grid">${card('Running',d.running?'Yes':'No')}${card('Cursor',d.cursor)}${card('Batch Size',d.batch_size)}${card('Last Run',d.last_run||'—')}</div><div class="actions"><button class="btn" onclick="runAction('adminStartDownloads')">Start Downloads</button><button class="btn secondary" onclick="runAction('adminStopDownloads')">Stop Downloads</button><button class="btn secondary" onclick="runAction('adminRetryFailedDownloads')">Retry Failed</button></div>`}
async function renderBundles(){const d=await api('adminBundleStatus');content.innerHTML=`<div class="grid">${card('Enabled',d.enabled?'Yes':'No')}${card('Last Run',d.last_run||'—')}</div><div class="actions"><button class="btn" onclick="runAction('adminStartBundleJob',{mode:'ALL'})">Start All Bundles</button><button class="btn secondary" onclick="runAction('adminPauseBundleJob')">Pause</button><button class="btn secondary" onclick="runAction('adminStopBundleJob')">Stop</button></div><pre>${esc(JSON.stringify(d,null,2))}</pre>`}
async function renderZips(){const d=await api('adminZipStatus');content.innerHTML=`<div class="grid">${card('Ready',d.ready??0,'status-ok')}${card('Missing',d.missing??0,'status-warn')}${card('Total',d.total??0)}</div><div class="actions"><button class="btn" onclick="runAction('adminBuildMissingZips')">Build Missing ZIPs</button></div>`}
async function renderDiagnostics(){content.innerHTML='<div class="actions"><button class="btn" onclick="runAction(\'adminRunHealthCheck\')">Run Health Check</button></div><div class="empty">Click Run Health Check. Results are written to the Diagnostics sheet.</div>'}
async function runAction(action,payload={}){try{setStatus('Running '+action+'…');const out=await api(action,payload);setStatus(action+' completed','status-ok');alert(JSON.stringify(out,null,2));loadPage(current)}catch(e){console.error(e);setStatus(e.message,'status-error');alert(e.message)}}
async function loadPage(p){current=p;title.textContent=p==='zips'?'ZIP Delivery':p[0].toUpperCase()+p.slice(1);document.querySelectorAll('[data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===p));try{setStatus('Connected to '+API,'status-ok');if(p==='dashboard')return renderDashboard();if(p==='orders')return renderOrders();if(p==='catalog')return renderCatalog();if(p==='queue')return renderQueue();if(p==='scanner')return renderScanner();if(p==='downloads')return renderDownloads();if(p==='bundles')return renderBundles();if(p==='zips')return renderZips();if(p==='diagnostics')return renderDiagnostics()}catch(e){console.error(e);setStatus(e.message,'status-error');content.innerHTML=`<div class="empty"><strong>Admin API error:</strong><br>${esc(e.message)}<br><br>Check Apps Script deployment, Script Properties and CORS/access settings.</div>`}}
document.querySelectorAll('[data-page]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();loadPage(a.dataset.page)}));document.getElementById('refreshBtn').addEventListener('click',()=>loadPage(current));loadPage('dashboard');