const $=id=>document.getElementById(id);let data={orders:[],catalogRows:[],system:{},queue:{},catalog:{},orderCounts:{}};
$('api').value=localStorage.getItem('studyhubAdminApi')||(window.STUDYHUB_CONFIG?.apiBaseUrl||'');
function getAuth(){const base=$('api').value.trim(),token=$('token').value.trim()||sessionStorage.getItem('studyhubAdminToken')||'';if(!base||!token)throw Error('Enter the API URL and private Admin token.');localStorage.setItem('studyhubAdminApi',base);sessionStorage.setItem('studyhubAdminToken',token);return{base,token}}
async function call(api,extra={}){const{base,token}=getAuth();const r=await fetch(base,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({api,token,...extra}),cache:'no-store'});const j=await r.json();if(!j.ok)throw Error(j.error||'Request failed');return j.data}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function msg(t,c=''){$('message').textContent=t;$('message').className='message '+c}
function paid(o){return['COMPLETE','MANUAL_PAID'].includes(String(o.pf_status).toUpperCase())}
function render(){const o=data.orders||[],c=data.catalogRows||[];const revenue=o.filter(paid).reduce((s,x)=>s+Number(x.amount_cents||0),0);$('stats').innerHTML=[['Orders',o.length],['Paid',o.filter(paid).length],['Pending',o.filter(x=>String(x.pf_status).toUpperCase()==='PENDING').length],['Delivered',o.filter(x=>String(x.delivery_status).toUpperCase()==='DELIVERY_SENT').length],['Live bundles',c.filter(x=>String(x.published).toUpperCase()==='TRUE'&&String(x.zip_status).toUpperCase()==='READY').length],['Revenue','R '+(revenue/100).toFixed(2)]].map(x=>`<div class="stat"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');renderOrders();renderCatalog();renderReports();$('system').innerHTML=`<h2>System status</h2><pre>${esc(JSON.stringify({system:data.system,queue:data.queue,catalog:data.catalog,orderCounts:data.orderCounts},null,2))}</pre>`}
function renderOrders(){const term=$('search').value.toLowerCase(),sf=$('statusFilter').value;const list=(data.orders||[]).filter(o=>{const blob=[o.order_id,o.customer_email,o.customer_name,o.sku,o.title,o.pf_status,o.delivery_status].join(' ').toLowerCase();return(!term||blob.includes(term))&&(sf==='ALL'||String(o.pf_status).toUpperCase()===sf)});$('orders').innerHTML=list.length?list.map(orderCard).join(''):'<div class="message">No matching orders.</div>'}
function orderCard(o){const isPaid=paid(o),email=encodeURIComponent(o.customer_email||''),subject=encodeURIComponent('StudyHub order '+(o.order_id||''));return`<article class="order"><div class="order-head"><strong>${esc(o.order_id)}</strong><span class="pill ${isPaid?'paid':String(o.pf_status).includes('FAILED')?'failed':''}">${esc(o.pf_status||'PENDING')}</span></div><div class="order-grid"><div><small>Customer</small><b>${esc(o.customer_name||'—')}</b></div><div><small>Email</small><b>${esc(o.customer_email||'—')}</b></div><div><small>Bundle</small><b>${esc(o.sku||'—')}</b></div><div><small>Amount</small><b>R ${(Number(o.amount_cents||0)/100).toFixed(2)}</b></div><div><small>Delivery</small><b>${esc(o.delivery_status||'PENDING')}</b></div><div><small>Created</small><b>${esc(o.timestamp||'—')}</b></div></div><div class="order-actions"><button onclick="act('mark_paid','${esc(o.order_id)}')">Mark paid + deliver</button><button class="secondary" onclick="act('mark_unpaid','${esc(o.order_id)}')">Mark unpaid</button><button onclick="act('grant_download','${esc(o.order_id)}')">Grant download</button><button class="danger" onclick="act('revoke_download','${esc(o.order_id)}')">Revoke</button><button class="secondary" onclick="act('resend_email','${esc(o.order_id)}')">Resend email</button><button class="danger" onclick="act('mark_refunded','${esc(o.order_id)}')">Mark refunded</button><button class="secondary" onclick="addNote('${esc(o.order_id)}')">Add note</button><a href="mailto:${email}?subject=${subject}">Open email</a>${o.zip_url?`<a href="${esc(o.zip_url)}" target="_blank">Open ZIP</a>`:''}${o.invoice_url?`<a href="${esc(o.invoice_url)}" target="_blank">Invoice</a>`:''}</div>${o.admin_notes?`<div class="message"><b>Notes:</b> ${esc(o.admin_notes)}</div>`:''}</article>`}
function renderCatalog(){const term=$('catalogSearch').value.toLowerCase(),state=$('catalogState').value;const list=(data.catalogRows||[]).filter(x=>{const live=String(x.published).toUpperCase()==='TRUE'&&String(x.zip_status).toUpperCase()==='READY';const okState=state==='ALL'||(state==='LIVE'&&live)||(state==='READY'&&String(x.zip_status).toUpperCase()==='READY')||(state==='HIDDEN'&&!live);return okState&&(!term||[x.sku,x.title,x.grade,x.subject_or_all,x.year_or_range].join(' ').toLowerCase().includes(term))});$('catalogList').innerHTML=list.length?list.map(x=>`<article class="order catalog-card"><div class="order-head"><strong>${esc(x.title||x.sku)}</strong><span class="pill ${String(x.published).toUpperCase()==='TRUE'?'paid':''}">${String(x.published).toUpperCase()==='TRUE'?'LIVE':'HIDDEN'}</span></div><div class="order-grid"><div><small>SKU</small><b>${esc(x.sku)}</b></div><div><small>Grade</small><b>${esc(x.grade)}</b></div><div><small>Subject</small><b>${esc(x.subject_or_all)}</b></div><div><small>Pairs</small><b>${esc(x.pair_count)}</b></div><div><small>Price</small><b>R ${(Number(x.price_cents||0)/100).toFixed(2)}</b></div></div><div class="order-actions"><button onclick="catalogAct('${String(x.published).toUpperCase()==='TRUE'?'unpublish':'publish'}','${esc(x.sku)}')">${String(x.published).toUpperCase()==='TRUE'?'Unpublish':'Publish'}</button><button class="secondary" onclick="catalogAct('${String(x.enabled).toUpperCase()==='FALSE'?'enable':'disable'}','${esc(x.sku)}')">${String(x.enabled).toUpperCase()==='FALSE'?'Enable':'Disable'}</button>${x.zip_url?`<a href="${esc(x.zip_url)}" target="_blank">Open ZIP</a>`:''}</div></article>`).join(''):'<div class="message">No matching catalog items.</div>'}
function renderReports(){const o=data.orders||[],paidOrders=o.filter(paid),revenue=paidOrders.reduce((s,x)=>s+Number(x.amount_cents||0),0),bySku={};paidOrders.forEach(x=>bySku[x.sku]=(bySku[x.sku]||0)+1);const top=Object.entries(bySku).sort((a,b)=>b[1]-a[1])[0]||['No sales',0];$('reports').innerHTML=[['Gross confirmed revenue','R '+(revenue/100).toFixed(2)],['Paid orders',paidOrders.length],['Pending orders',o.filter(x=>String(x.pf_status).toUpperCase()==='PENDING').length],['Refunded',o.filter(x=>String(x.pf_status).toUpperCase()==='REFUNDED').length],['Top SKU',top[0]],['Top SKU sales',top[1]]].map(x=>`<div class="report-card"><strong>${esc(x[1])}</strong><small>${x[0]}</small></div>`).join('')}
async function load(){try{msg('Loading Admin data...');data=await call('adminSummary');$('loginPanel').hidden=true;$('adminShell').hidden=false;render();msg('Admin data loaded.','ok')}catch(e){msg(e.message,'error')}}
window.act=async(action,order_id)=>{if(!confirm(`Run ${action} for ${order_id}?`))return;try{msg('Working...');await call('adminAction',{action,order_id});await load()}catch(e){msg(e.message,'error')}};
window.catalogAct=async(action,sku)=>{if(!confirm(`${action} ${sku}?`))return;try{await call('adminAction',{action,sku});await load()}catch(e){alert(e.message)}};
window.addNote=async order_id=>{const note=prompt('Admin note');if(!note)return;try{await call('adminAction',{action:'add_note',order_id,note});await load()}catch(e){alert(e.message)}};
function csv(rows,name){if(!rows.length)return;const keys=Object.keys(rows[0]),q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const blob=new Blob([keys.map(q).join(',')+'\n'+rows.map(r=>keys.map(k=>q(r[k])).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('connect').onclick=load;$('refresh').onclick=load;$('refreshCatalog').onclick=load;$('search').oninput=renderOrders;$('statusFilter').onchange=renderOrders;$('catalogSearch').oninput=renderCatalog;$('catalogState').onchange=renderCatalog;$('exportOrders').onclick=()=>csv(data.orders||[],'StudyHub_Orders.csv');$('exportCatalog').onclick=()=>csv(data.catalogRows||[],'StudyHub_Catalog.csv');$('lock').onclick=()=>{sessionStorage.removeItem('studyhubAdminToken');location.reload()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab-panel').forEach(x=>x.hidden=true);$(b.dataset.tab+'Tab').hidden=false});
